### ISSUE TITLE
I'm not sure if configuration is right

### ISSUE THREAD

**Issue by geaplanet** [SirSAC/DisPro#4]
This is my list output:
2021/08/18 11:33:40  [-] Listing the available addresses for dispatching
2021/08/18 11:33:41  [+] Ethernet 2, IP: fe80::7c27:b690:474b:5c4c
2021/08/18 11:33:41  [+] Ethernet 2, IP: 192.168.56.1
2021/08/18 11:33:41  [+] Wi-Fi, IP: fe80::a490:e1da:84af:2d74
2021/08/18 11:33:41  [+] Wi-Fi, IP: 192.168.43.145
2021/08/18 11:33:41  [+] Wi-Fi 2, IP: fe80::3cbc:9b4b:b40:23da
2021/08/18 11:33:41  [+] Wi-Fi 2, IP: 192.168.0.23

I copied/pasted the example configuration changing wifi ip:
DisProWindows.bin -host ::1 -port 1080 -multiply 2 -pipe 8192 -option -secure -delay -keep -serial 192.168.0.23 192.168.43.145

I installed foxyproxy in Firefox with this configuration:

![screenshot 11](https://user-images.githubusercontent.com/1422345/129876042-317a2380-8040-4d3e-ad8a-8972dbcad5e2.png)

Is there anything else I have to do?

Everything seems to work fine.

**Comment by SirSAC** [comment]
just write `DisPro.exe 192.168.0.23 192.168.43.145` and default IP and Port is `[::1]:8080`

**Comment by SirSAC** [comment]
sry, my bad, the port is `1080` and on firefox not need an extension, just go on firefox settings and u will find the proxy menu somewhere.

**Comment by SirSAC** [comment]
please replay me if is better or bad than ur soft from extremecoders-re and node soft.

**Comment by geaplanet** [comment]
The speed I got is similar to go-dispath-proxy. I did not get to test the old versions because installing node to fill my disk with crap gives me incredible laziness.

**Comment by SirSAC** [comment]
thanks for reply, this is un expected results because on my pc is total difference, go-dispatch-proxy is good but for me the upgraded version is much faster, low latency for some games, more options, much stable and more clean code i think.
yea node is not good for hdds and maybe not for ssd too in lifespan, if u see some differences just tell me please i really need some testers for improving my upgraded version of go-dispatch-proxy, thanks and have a nice day sir.
